default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: riku
  password: rikumysql1019
  host: localhost
  socket: /tmp/mysql.sock


development:
  <<: *default
  database: blog_app_development

test:
  <<: *default
  database: blog_app_test

production:
  <<: *default
  database: blog_app_production
  username: blog_app
  password: <%= ENV['BLOG_APP_DATABASE_PASSWORD'] %>